### ISSUE TITLE
Sim800C Reset Pin

### ISSUE THREAD

**Issue by erdemts** [MaJerle/gsm-at-lib#32]
Hi Majerle,
I'm using Sim800C. It hasn't got a reset pin. in gsm.c i added defines below. fyi.

#if defined(GSM_RESET_PIN)
            /* Try with hardware reset */
            if (gsm.ll.reset_fn != NULL && gsm.ll.reset_fn(1)) {
                gsm_delay(2);
                gsm.ll.reset_fn(0);
                gsm_delay(500);
            }
#endif

            /* Send manual AT command */
            AT_PORT_SEND_BEGIN_AT();

**Comment by MaJerle** [comment]
I don't catch why did you do it this way?
If you do not have reset pin, you can still reset it with AT command that is implemented in the lib.

**Comment by erdemts** [comment]
Thanks
